In [12]:
import pandas as pd
import numpy as np

In [13]:
df=pd.read_csv("/content/titanic.csv")

In [14]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S

In [15]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [16]:
df=df.drop(columns=["Cabin","Ticket"])

In [17]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
Embarked        0
dtype: int64

In [18]:
from sklearn.impute import SimpleImputer

In [19]:
si=SimpleImputer(strategy='mean')

In [20]:
df["Age"]=si.fit_transform(df[["Age"]])

In [21]:
df["Fare"]=si.fit_transform(df[["Fare"]])

In [22]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [23]:
df=pd.get_dummies(df,columns=["Name","Sex","Embarked"])

In [24]:
df.head(1)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbott, Master. Eugene Joseph","Name_Abelseth, Miss. Karen Marie","Name_Abelseth, Mr. Olaus Jorgensen",...,"Name_de Brito, Mr. Jose Joaquim","Name_de Messemaeker, Mr. Guillaume Joseph","Name_del Carlo, Mrs. Sebastiano (Argenia Genovesi)","Name_van Billiard, Master. James William","Name_van Billiard, Master. Walter John",Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,34.5,0,0,7.8292,False,False,False,...,False,False,False,False,False,False,True,False,True,False

In [25]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
              ..
Sex_female     0
Sex_male       0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
Length: 430, dtype: int64

In [26]:
df.astype(int)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbott, Master. Eugene Joseph","Name_Abelseth, Miss. Karen Marie","Name_Abelseth, Mr. Olaus Jorgensen",...,"Name_de Brito, Mr. Jose Joaquim","Name_de Messemaeker, Mr. Guillaume Joseph","Name_del Carlo, Mrs. Sebastiano (Argenia Genovesi)","Name_van Billiard, Master. James William","Name_van Billiard, Master. Walter John",Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,34,0,0,7,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,893,1,3,47,1,0,7,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,894,0,2,62,0,0,9,0,0,0,...,0,0,0,0,0,0,1,0,1,0
3,895,0,3,27,0,0,8,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,896,1,3,22,1,1,12,0,0,0,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,30,0,0,8,0,0,0,...,0,0,0,0,0,0,1,0,0,1
414,1306,1,1,39,0,0,108,0,0,0,...,0,0,0,0,0,1,0,1,0,0
415,1307,0,3,38,0,0,7,0,0,0,...,0,0,0,0,0,0,1,0,0,1
416,1308,0,3,30,0,0,8,0,0,0,...,0,0,0,0,0,0,1,0,0,1
417,1309,0,3,30,1,1,22,0,0,0,...,0,0,0,0,0,0,1,1,0,0

In [27]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
dt=DecisionTreeClassifier()

In [32]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [33]:
y_pred=dt.predict(x_test)

In [34]:
from sklearn.metrics import accuracy_score

In [35]:
accuracy_score(y_test,y_pred)

1.0